### ISSUE TITLE
Error retrieving all or single Refund for an order

### ISSUE THREAD

**Issue by mnaeem76** [XiaoFaye/WooCommerce.NET#484]
It seems Refunds part of the API is not working correctly. API throws exception while retrieving refunds for an order.

Please see the code below:

`var refundsForOrder = wc.Order.Refunds.GetAll(orderId).Result;`

OR

`var refund = wc.Order.Refunds.Get(refundId, orderId).Result;`

Fiddler request for GetAll 
![image](https://user-images.githubusercontent.com/65190008/84149201-822d6800-aa79-11ea-939b-0a336aa1a39f.png)

Fiddler response with data comes in correctly. Please see the image
![image](https://user-images.githubusercontent.com/65190008/84150442-4f846f00-aa7b-11ea-8599-63832e5ffbbc.png)

For single refund using Get
![image](https://user-images.githubusercontent.com/65190008/84150906-fbc65580-aa7b-11ea-8f49-40cbe5ae4ec8.png)

Response for single comes in correctly as well
![image](https://user-images.githubusercontent.com/65190008/84151095-4647d200-aa7c-11ea-9a07-1fce1f883922.png)

I'm attaching here a file with details of the exception. In a nutshell it is a format exception.  Somewhere in the API when it parses data returned from the REST API.  
[GetRefundException.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/4752335/GetRefundException.txt)

Using the PHP library for integration works fine and that's how I was able to detect there might be problem in .NET API. Kindly help resolve this issue.

Please also note that you had provided me with an updated version of the assembly in response to my previously reported issue: https://github.com/XiaoFaye/WooCommerce.NET/issues/476. I have been using that version instead of the official 0.8.2 version. I'll be pushing a build of my application to LIVE very soon using that version. If this issue I'm reporting now should allow you to send me a new assembly to test/use, please make sure it would retain that fix as well.

Thanks,
Mudasser

 ### Make sure you have included the below details when open an issue. Thank you.

- Wordpress version 5.4.1, WooCommerce version 4.0.1 and WooCommerce.NET version 0.8.2

- Use API to get list of refunds for an order or get a single refund by refund it and order id

-  There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v3.OrderRefund, WooCommerce.NET, Version=0.8.2.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. The value '' cannot be parsed as the type 'Int32'.

**Comment by mnaeem76** [comment]
Addendum: I think it is caused by **tax_class** field in the **OrderRefundItem** class. In my particular case, tax class is an empty string returned by the REST API. I'm attaching here the sample JSON response which works fine if tax_class is set to "0" (as it is set in this file). The original response had "" (empty string). I suspect that is the cause of the issue. 

Looking through the WooCommerce documentation, tax class only get returned if it was setup and it is not mandatory. Even if it was set, it won't return for such orders that are tax free. So I believe change in the data type of this field in question should be changed or whatever is appropriate you think should be the case. 

[SampleJsonResponse.txt](https://github.com/XiaoFaye/WooCommerce.NET/files/4753006/SampleJsonResponse.txt)

Thanks
Mudasser

**Comment by XiaoFaye** [comment]
You can try to replace the return json string, tax_class:"" -> tax_class:"0" , see if it's working.

**Comment by mnaeem76** [comment]
That’s what I did. I pulled in the raw JSON string response using HttpClient and HttpRequestMessage bypassing the .net API. I hope this issue gets resolved in upcoming versions of the .net API so one does not need to write code to bypass it.

**Comment by XiaoFaye** [comment]
Sure, this has been added to version 0.8.3

**Comment by XiaoFaye** [comment]
Hi, this is fixed in version 0.8.3.

**Comment by Fashionepaul** [comment]
Hi, this problem still happens with the 0.8.3 release.

In the json response I receive it is received as `"tax_class": ""`

I think you would probably need to use `string?` instead of `int?`, for the `tax_class` field.
