### ISSUE TITLE
Error on Deserialize WooCommerceNET.Base.BatchObject<Variation>

### ISSUE THREAD

**Issue by nvsoares** [XiaoFaye/WooCommerce.NET#523]
The deserialization of the response in variations batch delete is giving the following error: 

System.Exception {System.Runtime.Serialization.SerializationException}
An error occurred when canceling the serialization of the object of type 
WooCommerceNET.Base.BatchObject`1[[WooCommerceNET.WooCommerce.v3.Variation, WooCommerce.NET, Version=0.8.2.0, Culture=neutral, PublicKeyToken=ff41d0b6c937438d]]. The value '' cannot be parsed as the type 'Int32'

Here is a code snippet to demonstrate how to cause the error:

```
List<WooCommerceNET.WooCommerce.v3.Variation> variations = await this.WCObject.Product.Variations.GetAll(Product.EUID, parms);
List<int> ids = variations.Select(v => v.id.Value).ToList();

WooCommerceNET.Base.BatchObject<Variation> myVariation = new WooCommerceNET.Base.BatchObject<Variation>();
myVariation.delete = ids;
await WCObject.Product.Variations.UpdateRange(Product.EUID, myVariation);
```

We think the problem is due to the fact that we send a list of integers and the response returns a list of variations.
Thanks

**Comment by XiaoFaye** [comment]
You are right, that was the issue, I will see what I can do to fix this issue.

**Comment by nvsoares** [comment]
Hello, we need to go into production in the next few days. Do you know when it might be fixed?

 

 

Cumprimentos,

 

Nuno Soares

 <mailto:nuno.vsoares@gmail.com> nuno.vsoares@gmail.com

968927063

 

De: James Yang <notifications@github.com> 
Enviada: 16 de setembro de 2020 21:55
Para: XiaoFaye/WooCommerce.NET <WooCommerce.NET@noreply.github.com>
Cc: Nuno Soares <nuno.vsoares@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [XiaoFaye/WooCommerce.NET] Error on Deserialize WooCommerceNET.Base.BatchObject<Variation> (#523)

 

You are right, that was the issue, I will see what I can do to fix this issue.

**Comment by nvsoares** [comment]
Hi, we need to go into production in the next few days. Do you know when it might be fixed?

**Comment by XiaoFaye** [comment]
Actually you can ignore this exception, as the deletion is success, just the deserialization of response fail, which won't affect the functionality.

**Comment by nvsoares** [comment]
I will do so. But I am afraid to ignore other mistakes that should not be ignored.

**Comment by Bokkeman** [comment]
> 
> 
> I will do so. But I am afraid to ignore other mistakes that should not be ignored.

Until this gets fixed, our workaround is to split the batch into two: the first lot contains all the add's and update's where we apply normal error handling, and the second just the delete's where we ignore this null-reference exception

**Comment by XiaoFaye** [comment]
Hi, this is fixed in version 0.8.3.

**Comment by firestormza** [comment]
This is still an issue when using `WCSubItem<T>.UpdateRange()` for updating `Variations`, etc.
The same fix applied to `WCItem<T>.UpdateRange()`  should also be to `WCSubItem<T>.UpdateRange()`
Source Commit: [Fix Error on Deserialize BatchObject. #523](https://github.com/XiaoFaye/WooCommerce.NET/commit/4cf6fb1fbc495e7d084b00ae72291765c9440940)
